name = input("请输入姓名：")
sex = input("请输入性别：")
age = input("请输入年龄：")
phone = input("请输入号码：")
addr = input("请输入家庭住址：")
email = input("请输入邮箱号码：")
print("信息录入完毕")
print('*'*30)
print("姓名：%s\n性别：%s\n年龄：%s\n号码：%s\n家庭住址：%s\n邮箱：%s"%(name,sex,age,phone,addr,email))
print('*'*30)
